config/routes.rb
Rails.application.routes.draw do
  
  get 'home/about'
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  resources :users, only: [:show, :index, :create, :edit, :update]

  resources :root, only: [:top]
  
  root 'root#top'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence:true,uniqueness: true, length: {minimum: 2,maximum: 20}
  #validates :introduction,length: {minimum: 3 ,maximum: 50}

  attachment :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :authenticate_user!,except: [:top, :about]

	def after_sign_in_path_for(resource)
    	user_path(current_user.id)
    end

    before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	  def configure_permitted_parameters
	    #strong parametersを設定し、usernameを許可
	    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation) }
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def new
    	@book = Book.new
    end
    def create
    	@book = Book.new
    	@book = Book.new(book_params)
    	@book.user_id = current_user.id
    	@book.save
    	redirect_to books_path
    end
    
    def index
        @book = Book.new
    	@books = Book.all
        @user = current_user
    end
    
    def show
        @book = Book.new
    	@boook = Book.find(params[:id])
        @user = User.find(current_user.id)
    end

    def edit
        @book = Book.new
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        redirect_to book_path(@book.id)
    end

    private
    def book_params
    	params.require(:book).permit(:book_title, :book_body,  :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@book = Book.new
  	@user = User.find(current_user.id)
  	@users = User.all
  end

  def show
  	@book = Book.new
    @books = User.find(params[:id]).books.all
  	@user = User.find(params[:id])
  end

  def create
    @book = Book.new
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook-form.html.erb
<h2>New book</h2>
	<%= form_for(@book, url:books_path) do |f| %>
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<div class="row">
			<div class="col-md-12">
				<label>Title</label><br>
				<%= f.text_field :book_title, class:"book_title" %>
			</div>
		</div>
			<br>
		<div class="row">
			<div class="col-md-12">
				<label>opinion</label><br>
				<%= f.text_area :book_body, class:"book_body" %>
			</div>
		</div>
			<div class="col-md-12">
				<%= f.submit "Create Book", class:"btn btn-primary " %>
			</div>
	<% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h2>Editing book</h2>
			<%= form_for(@book) do |f| %>
				<p>title</p>
				<%= f.text_field :book_title, class:"book_title" %>
				<p>opinion</p>
				<%= f.text_area :book_body, class:"book_boby" %>
				<%= f.submit 'Update Book' %>
			<% end %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<html>
<head>
</head>

<body>
	<div class='body'>
			<div class= 'container'>

				<p id= "notice"></p>

				<div class="row">
					<div class="col-md-3">

						<%= render 'users/user-info-section',user: @user %>

						<div class="row">
							<div class="col-md-12">

								<%= render 'books/newbook-form',book:@book %>

							</div>
						</div>
					</div>

							<div class = 'col-md-9'>
								<h2>Books</h2>
								<table class ='table table-hover table-inverse'>
									<thead>
										<tr>
											<th></th>
											<th>Title</th>
											<th>Opinion</th>
											<th clospan="3"></th>
										</tr>
									</thead>

									<tbody>
									<% @books.each do |book| %>
										<tr>
											<td>
												<%= link_to user_path(book.user.id)do %>
													<%= attachment_image_tag book.user, :image, :fill, 30, 30,fallback: "no_image.jpg", format:'jpeg' %>
												<% end %>
											</td>
											<td><%= link_to "#{book.book_title}",book_path(book.id),class:"edit_book_#{book.id}" %></td>
											<td><%= book.book_body %></td>

											<!-- <td><%= link_to "Destroy",book_path(book.id),class:"destroy_book_#{book.id}",method: :delete %></td>-->
										</tr>
									<% end %>
									</tbody>
								</table>
							</div>
					</div>
				</div>
			</div>

</body>

app/views/books/new.html.erb
<!-- <form> -->
<%= form_for(@book, url: books_path) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-10">
      <label>Title</label>
      <%= f.text_field :book_title, class:"book_title" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      
        <label>opinion</label>
        <%= f.text_area :book_body, class:"book_body" %>
        
      </div>
  </div>
  <%= f.submit "Create Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>
<!-- </form> -->

app/views/books/show.html.erb
<html>
<head>
</head>

<body>
	<div class='body'>
			<div class= 'container'>
				
				<p id= "notice"></p>
				
				
				<div class="row">
					<div class="col-md-3">
						
						<%= render 'users/user-info-section',user: @boook.user %>
					
						<div class="row">
							<div class="col-md-12">
								
								<%= render 'books/newbook-form',book:@book %>

							</div>
						</div>
					</div>

							<div class = 'col-md-9'>
								<h2>Book Detail</h2>
								<table class ='table table-hover table-inverse'>
									<thead>
										<tr>
											<th></th>
											<th>Title</th>
											<th>Opinion</th>
											<th clospan="3"></th>
										</tr>
									</thead>
									
									<tbody>
										<tr>
											<td>
												<%= link_to user_path(@boook.user.id) do %>
													<%= attachment_image_tag @boook.user, :image, :fill, 30, 30,fallback: "no_image.jpg", format:'jpeg' %><br />
													<%= @boook.user.name %>
												<% end %>
											</td>
											<td><%= @boook.book_title %></td>
											<td><%= @boook.book_body %></td>
										    <td>
										    	<% if @boook.user == current_user %>
										    	  <%= link_to "Edit",edit_book_path(@boook.id),class:"edit_book_#{@boook.id}" %>
										    	<% end %>
										    </td>
											<td>
												<% if @boook.user == current_user %>
												  <%= link_to "Destroy",book_path(@boook.id),class:"destroy_book_#{@boook.id}",method: :delete %>
												<% end %>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
					</div>
				</div>
			</div>

</body>

app/views/home/about.html.erb
<h1>WELCOME TO BOOKERS!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers2</span>
        </nav>
        <nav>
         <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to "Home","/", class:"home" %>
            </li>
            <li class="">
              <%= link_to "Users",users_path,class:"users" %>
            </li>
            <li class="">
              <%= link_to "Books",books_path,class:"books" %>
            </li>
            <li>
              <%= link_to "Log out",destroy_user_session_path, method: :delete,class:"logout" %>
            </li>
          <% else %>
            <li class="">
              <%= link_to "Home","/",class:"home" %>
            </li>
            <li class="">
              <%= link_to "About",home_about_path, class:"about" %>
            </li>
            <li>
              <%= link_to "Sign up",new_user_registration_path,class:"sign_up" %>
            </li>
            <li>
              <%= link_to "Log in",new_user_session_path,class:"sign_in" %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    
    
    
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
  </body>
</html>

app/views/root/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>welcome to Bookers  !!</h1>
			<%= link_to "Log in",new_user_session_path, class:"sign_in" %>
			<%= link_to "Sign up",new_user_registration_path, class:"sign_up" %>
		</div>
	</div>
</div>

app/views/users/_user-info-section.html.erb
<h2>User Info</h2>

	<table class='table'>
		<tr><%= attachment_image_tag user, :image, :fill, 100, 100,fallback: "no_image.jpg", format:'jpeg' %></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
	</table>

<%= link_to "my page",edit_user_path(current_user.id),class:"edit_user_#{current_user.id}" %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= form_for(@user) do |f| %>

	<label>Name</label>
	<%= f.text_field :name, class:"name" %>

	<label>Image</label>
	<%= f.attachment_field :image, class:"user_image" %>

	<label>Introduction</label>
	<%= f.text_field :introduction,class:"introduction" %>


	<%= f.submit "Update User" %>

<% end %>

app/views/users/index.html.erb
<html>
<head>
</head>

<body>
	<div class='body'>
			<div class= 'container'>
				
				<p id= "notice"></p>
				
				
				<div class="row">
					<div class="col-md-3">
						<p></p>
						<%= render 'users/user-info-section',user: @user %>
					
						<div class="row">
							<div class="col-md-12">

								<%= render 'books/newbook-form',book:@book %>

							</div>
						</div>
					</div>

							<div class = 'col-md-9'>
								<h2>Users</h2>
								<table class ='table table-hover table-inverse'>
									<thead>
										<tr>
											<th>Image</th>
											<th>Name</th>
											<th></th>
											<th clospan="3"></th>
										</tr>
									</thead>
									
									<tbody>
										<% @users.each do |user| %>
										<tr>
											<th><%= attachment_image_tag user,:image, :fill, 30, 30,fallback: "no_image.jpg", format:'jpeg' %></th>
											<th><%= user.name %></th>
											<th><%= link_to "Show",user_path(user.id),class:"user_#{user.id}" %></th>
										</tr>
										<% end %>
									</tbody>
								</table>
							</div>
					</div>
				</div>
			</div>
</body>

app/views/users/show.html.erb
<html>
<head>
</head>
<body>
	<div class='body'>
			<div class= 'container'>

				<p id= "notice"></p>

				<div class="row">
					<div class="col-md-3">

						<%= render 'users/user-info-section',user: @user %>

						<div class="row">
							<div class="col-md-12">

								<%= render 'books/newbook-form',book:@book %>


							</div>
						</div>
					</div>
							<div class = 'col-md-9'>
								<h2>Books</h2>
								<table class ='table table-hover table-inverse'>
									<thead>
										<tr>
											<th></th>
											<th>Title</th>
											<th>Opinion</th>
											<th clospan="3"></th>
										</tr>
									</thead>

									<tbody>
										<% @books.each do |book| %>
										<tr>
											<td><%= attachment_image_tag book.user, :image, :fill, 30, 30,fallback: "no_image.jpg", format:'jpeg' %></td>
											<td><%= link_to "#{book.book_title}",book_path(book.id),class:"book_#{book.id}" %></td>
											<td><%= book.book_body %></td>
										</tr>
										<% end %>
									</tbody>
								</table>
							</div>
				</div>
			</div>
	</div>
</body>
</html>